name: 'Generate Documentation'
description: 'Генерирует документацию из комментариев кода'
inputs:
  source-dir:
    description: 'Папка с исходным кодом'
    required: true
    default: 'src'
  output-dir:
    description: 'Папка для документации'
    required: true
    default: 'docs'

runs:
  using: 'composite'
  steps:
    - name: Установка зависимостей
      shell: bash
      run: sudo apt-get install -y doxygen

    - name: Генерация документации
      shell: bash
      run: |
        echo "Генерация документации для ${{ inputs.source-dir }}..."
        doxygen Doxyfile
      env:
        INPUT_SOURCE_DIR: ${{ inputs.source-dir }}
        OUTPUT_DIR: ${{ inputs.output-dir }}

    - uses: actions/upload-artifact@v4
      with:
        name: generated-docs
        path: ${{ inputs.output-dir }}
