name: Docs Generator
on:
  push:
    branches: [ main ]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Make script executable
          run: |
            cd scripts
            chmod +x generate-docs.sh

        - name: Run script
          run: |
            cd scripts
            ./generate-docs.sh
          shell: bash

        - name: Деплой документации
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs
